name: "jest coverage report "
github-token:
  action-input:
    input: github-token
    is-default: true
  permissions:
    pull-requests: write
    pull-requests-reason: to comment on pull request
    #Reference: https://github.com/ArtiomTr/jest-coverage-report-action/blob/e1023a86c8d1ba542bfaa9a18a9efe55ef494c8a/src/typings/Options.ts
