name: "OWASP ZAP Full Scan"
github-token:
  action-input:
    input: token
    is-default: true
  permissions:
    issues: write
    issues-reasons: to create issues in the repository
    #Reference: https://github.com/zaproxy/action-full-scan/blob/6eade0f93b10fad8cfb4e63b979703a2cbd0cc98/index.js#L17
