name: "Yarn Audit"
github-token:
  action-input:
    input: GITHUB_TOKEN
    is-default: false
  permissions:
    actions: read
    actions-reasons: to run yarn audit command
    issues: write
    issues-reasons: to create Github issues
    #Reference: https://github.com/pragatheeswarans/yarn-audit-action/blob/f3ab4c055f4b8f1db1b1ae0e32bab690c9050603/index.js
