name: "Code Coverage Report"
github-token:
  action-input:
    input: github_token
    is-default: true
  permissions:
    actions: write
    actions-reson: to comment PRs with code coverage report
    pull_requests: write
    pull-requests-reason: to commit the comment
    #Reference: https://github.com/eberlitz/lcov-reporter-action
    #https://github.com/romeovs/lcov-reporter-action
